

-- Tabela temporária contendo somente os registros das filas necessárias
SELECT 
    A.COD_MENS,
    A.DAT_HOR_INCU,
    A.DAT_HOR_PSST,
    A.DAT_HOR_ERRO,
    A.DAT_HOR_EXCU,
    A.NOM_FILR,
    TIPO = @MERCADO
INTO #TBFR6002_CTRL_MSGR
FROM utilitario.TBFR6002_CTRL_MSGR (NOLOCK) A
WHERE 
    (A.DAT_HOR_INCU >= @DATABASE_START_DATE OR @DATABASE_START_DATE IS NULL) AND
    (A.DAT_HOR_INCU < @DATABASE_END_DATE OR @DATABASE_END_DATE IS NULL) AND
    A.NOM_FILR IN (
        SELECT B.NOM_FILR 
        FROM #TMP_FILAS_MENSAGERIA AS B
        WHERE B.TIPO = @MERCADO
    );
